# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
environment_name="dev"
project_name="lincoln"
resource_name="ec2"
remote_state_bucket_name="lincoln-dev-s3-terraform-state"
tags={
    Owner="jordan.kim"
}

ec2_atlantis_instnace_type = "t2.micro"