# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# 리소스를 파일 여러개로 관리할 거면 여기에 ResourceName_NameTag 로 생성


resource "tls_private_key" "this" {
  algorithm = "RSA"
  rsa_bits = 4096
  
  provisioner "local-exec" {
    command = "echo '${tls_private_key.this.private_key_pem}' > ./${var.project_name}-${var.resource_name}-${var.environment_name}.pem"
  }
  
}

module "key_pair" {
  source = "../../../../../../../modules/keypair"

  key_name   = "${var.project_name}-${var.resource_name}-${var.environment_name}"
  public_key = tls_private_key.this.public_key_openssh
}