# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
environment_name="dev"
project_name="lincoln"
resource_name="eks"
remote_state_bucket_name="lincoln-s3-dev-terraform-state"
tags={
    Owner="jordan.kim"
}
