# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "lincoln-dev-s3-terraform-state"
    dynamodb_table = "lincoln-dev-ddb-tfstate-lock-global-iam"
    encrypt        = true
    key            = "global/iam/terraform.tfstate"
    region         = "ap-northeast-2"
  }
}
