# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "lincoln-dev-s3-terraform-state"
    dynamodb_table = "lincoln-dev-ddb-terraform-state-lock-global-ddb"
    encrypt        = true
    key            = "global/ddb/terraform.tfstate"
    region         = "ap-northeast-2"
  }
}
