# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# 리소스를 파일 여러개로 관리할 거면 여기에 ResourceName_NameTag 로 생성

resource "aws_dynamodb_table" "lincoln-terraform-state-lock" {
  for_each = var.lock_name   
  name = "${var.project_name}-${var.environment_name}-${var.resource_name}-tfstate-lock-${each.value}"
  read_capacity = 5     
  write_capacity = 5 
  hash_key = "LockID" 

  attribute {
    name = "LockID"
    type = "S"  
  } 

   tags = merge(
       {
            name     = "${var.project_name}-${var.environment_name}-${var.resource_name}-tfstate-lock-${each.value}"
            createdBy = "jordan.kim"
       },
       var.tags 
   )    
}