# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
environment_name="dev"
project_name="lincoln"
resource_name="vpc"
vpcs_name="app"
remote_state_bucket_name="lincoln-s3-dev-terraform-state"
tags={ 
    Owner = "jordan.kim"
}

vpc_cidr="10.10.1.0/24"
secondary_cidr=[
    "10.10.2.0/24",
    "10.10.3.0/24",
    "10.10.4.0/24",
    "10.10.5.0/24"
]

public_cidr=[
    "10.10.1.0/25", 
    "10.10.1.128/25"
]
public_subnet_suffix="subnet-public"
public_route_suffix="route-public"

private_cidr = [
    "10.10.2.0/25", 
    "10.10.2.128/25",
    "10.10.3.0/25", 
    "10.10.3.128/25",
    "10.10.4.0/25", 
    "10.10.4.128/25",
    "10.10.5.0/25",
    "10.10.5.128/25"
]
private_subnet_azs=[
    "ap-northeast-2a",
    "ap-northeast-2c",
    "ap-northeast-2a",
    "ap-northeast-2c",
    "ap-northeast-2a",
    "ap-northeast-2c",
    "ap-northeast-2a",
    "ap-northeast-2c",
]
private_subnet_suffix=[
    "subnet-private-ingress",
    "subnet-private-ingress",
    "subnet-private-app",
    "subnet-private-app",
    "subnet-private-mgmt",
    "subnet-private-mgmt",
    "subnet-private-db",
    "subnet-private-db"
]
private_route_suffix=[
    "route-private-ingress",
    "route-private-app",
    "route-private-mgmt",
    "route-private-db",
]

private_subnet_index=[
    0,
    0,
    1,
    1,
    2,
    2,
    3,
    3
]




