# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
environment_name="dev"
project_name="test2"
resource_name="eks"
remote_state_bucket_name="lincoln-dev-s3-terraform-state"
tags={
    Owner="jordan.kim"
}
lincoln_aws_account_id="661078097983"
eks_ami_id="ami-06512ccb913a9d11d" 