# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "region" {
    default = "ap-northeast-2"
}  

variable "environment_name" {
}

variable "project_name" {
}

variable "resource_name" {
}

variable "tags" {
}

variable "remote_state_bucket_name" {
}

variable "lincoln_aws_account_id" {
    
}

variable "eks_ami_id" {
    
}