# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# 리소스를 파일 하나로 관리할 거면 여기에

# ##############################################################################################################
# EKS
# create EKS cluster & node groups
# ##############################################################################################################
provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
}

module "eks" {

  source          = "../../../../../../../modules/eks"
  
  cluster_name    = "${var.project_name}-${var.resource_name}-${var.environment_name}"
  cluster_version = "1.22"

  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true 

  node_security_group_use_name_prefix = "false"
  cluster_security_group_use_name_prefix = "false"

  cluster_addons = {
    coredns = {
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {}
    # vpc-cni = {
    #   resolve_conflicts = "OVERWRITE"
    # }
  }

  vpc_id          = data.terraform_remote_state.vpc.outputs.vpc[0].vpc_id
  subnet_ids      = [data.terraform_remote_state.vpc.outputs.vpc[0].private_subnets[0],
                      data.terraform_remote_state.vpc.outputs.vpc[0].private_subnets[1],
                      data.terraform_remote_state.vpc.outputs.vpc[0].private_subnets[2],
                      data.terraform_remote_state.vpc.outputs.vpc[0].private_subnets[3],
                      data.terraform_remote_state.vpc.outputs.vpc[0].private_subnets[4],
                      data.terraform_remote_state.vpc.outputs.vpc[0].private_subnets[5]
                    ]
  cloudwatch_log_group_retention_in_days = 1

  # EKS Managed Node Group(s)
  eks_managed_node_group_defaults = local.node_group_defaults
  eks_managed_node_groups = local.node_groups

  # aws-auth configmap
  manage_aws_auth_configmap = true
  # aws_auth_users            = local.aws_auth_users
  # aws_auth_accounts         = local.aws_auth_accounts

  tags = merge(
    {
      "Name" = "${var.project_name}-${var.resource_name}-${var.environment_name}-eks-cluster"
    },
    var.tags
  )

}


